language: rust
cache:
    - cargo
rust:
    - stable
    - beta
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly

script:
    - |
      if [[ "$TRAVIS_RUST_VERSION" == nightly ]]
      then
        cargo install grcov -f
        export CARGO_INCREMENTAL=0
        export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
      fi
    - cargo test --all-targets
    - |
      if [[ "$TRAVIS_RUST_VERSION" == nightly ]]
      then
        zip -0 ccov.zip `find . \( -name "*.gc*" \) -print`;
        grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" > lcov.info;
        bash <(curl -s https://codecov.io/bash) -f lcov.info;
      fi
